apiVersion: automation.cloudbees.io/v1alpha1
kind: action
name: 'Kaniko build and push'
description: 'Build and publish Docker images from a Dockerfile using Kaniko'
inputs:
  dockerfile:
    description: 'Path to the Dockerfile'
    default: Dockerfile
  context:
    description: 'Docker build context'
    default: ${{ cloudbees.workspace }}
  destination:
    description: >
      Target image(s) that will be published to the registries configured in the file ${HOME}/.docker/config.json
      Type: CSV
    required: true
  build-args:
    description: >
      Docker build arguments.
      Type: CSV
  labels:
    description: >
      Metadata to be associated with the resulting image.
      Type: CSV
outputs:
  digest:
    value: ${{ steps.imgbuild.outputs.digest }}
    description: Image digest (image ID)
runs:
  using: composite
  steps:
    - id: imgbuild
      name: Build and publish Docker image
      uses: docker://registry.saas-dev.beescloud.com/staging/kaniko-action:0.0.3
      with:
        entrypoint: kaniko-action
        args: --dockerfile "${{ inputs.dockerfile }}" --context "${{ inputs.context }}" --destination "${{ inputs.destination }}"
      env:
        DOCKER_CONFIG: /cloudbees/home/.docker
        DOCKER_BUILD_ARGS: ${{ inputs.build-args }}
        DOCKER_LABELS: ${{ inputs.labels }}
