FROM node:18 AS build

WORKDIR /app
COPY package*.json ./

RUN npm install

COPY . .

RUN npm run build

FROM node:18-slim

WORKDIR /app

COPY --from=build /app/build /app/build
COPY --from=build /app/node_modules /app/node_modules
COPY --from=build /app/package*.json /app/

ENV NODE_ENV=production

EXPOSE 3000

CMD ["node", "build/index.js"]