= CloudBees action: Build and publish Docker images with Kaniko

Use the Kaniko action to build images based upon a Dockerfile, then publish the image to a Docker registry.
Kaniko builds images inside a container or Kubernetes cluster.
This action also reports the image and tag names to the workflow run for artifact traceability purposes.

== Prerequisites

To authenticate with the Docker registry, you must have a Docker config file in the `${HOME}/.docker/config.json` path.

Use link:https://github.com/cloudbees-io/configure-oci-credentials[the OCI credentials configuration action] to generate a Docker config file, as in the following example.

In your YAML file, add:

[source,yaml]
----

      - id: dockerconfig
        name: Configure container registry credentials
        uses: cloudbees-io/configure-oci-credentials@v1
        with:
          registry: ${{ vars.DOCKER_REGISTRY }}
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

----

The Docker config file must be formatted in JSON, as follows:
To use the following example, make these updates:

* Replace <REGISTRY_HOST> with your registry host URL.
* Replace <USERNAME> with your username.
* Replace <PASSWORD> with your password.

[source,json,role="novalidate"]
----
{
	"auths": {
		"<REGISTRY_HOST>": {
			"username": "<USERNAME>",
			"password": "<PASSWORD>",
			"auth": "<USERNAME>:<PASSWORD>"
		}
	}
}
----

NOTE: The `+"auth":"<USERNAME>:<PASSWORD>"+` field must be base64-encoded.


== Inputs

[cols="2a,1a,1a,3a",options="header"]
.Input details
|===

| Input name
| Data type
| Required?
| Description

| `destination`
| String
| Yes
| The locations of the target images to be published.
Formatted as a comma-separated list for passing multiple images.

| `build-args`
| String
| No
| The build arguments to be passed to the Kaniko build. 
Formatted as a comma-separated list for passing multiple build arguments.

| `context`
| String
| No
| The path to the build context.
Default is `${{ cloudbees.workspace }}`.

| `dockerfile`
| String
| No
| The path to the Dockerfile to be built.
Default is `Dockerfile`.

| `labels`
| String
| No
| The label metadata added to the final image.
Formatted as a comma-separated list for passing multiple labels.

| `labels`
| String
| No
| The label metadata added to the final image.
Formatted as a comma-separated list for passing multiple labels.

| `registry-mirrors`
| String
| No
| Registry mirrors to use for loading images.
Formatted as a comma-separated list for passing multiple registries.

| `skip-default-registry-fallback`
| Boolean
| No
| If set to 'true', fails build if `registry-mirrors` cannot pull the image.
If `registry-mirrors` is empty, this flag is ignored.
Default is 'false'.

| `tar-path`
| String
| No
| Full path location where the image is to be saved, including the filename.
To use this option, the image file must be in the TAR format.

| `verbosity`
| String
| No
| The verbosity of logging when running the Kaniko build.
Accepted inputs are: `panic`, `fatal`, `error`, `warn`, `info`, `debug`, `trace`.
Default is `info`.

|===

== Outputs

[cols="2a,1a,3a",options="header"]
.Output details
|===

| Output name
| Data type
| Description

| `artifact-id`
| String
| The unique identifier of the artifact reported to the CloudBees platform.
|===

== Usage examples

=== Basic example

The following is a basic usage example for this action:

[source,yaml]
----
      - name: Build a container image with Kaniko
        uses: cloudbees-io/kaniko@v1
        with:
          destination: path/to/registry/host/my-image:1.0.1,path/to/registry/host/my-image:latest
----

=== Using optional inputs

The following example specifies the build args, context, Dockerfile, labels, and verbosity:

[source,yaml]
----
      - name: Kaniko build with optional inputs
        uses: cloudbees-io/kaniko@v1
        with:
          destination: path/to/registry/host/my-image:1.0.1,path/to/registry/host/my-image:latest
          build-args: BUILDKIT_CONTEXT_KEEP_GIT_DIR=1,BUILDKIT_INLINE_CACHE=1
          context: .
          dockerfile: path/to/Dockerfile
          labels: maintainer=John Smith,version=1.0.1
          verbosity: warn

----

=== Using action outputs

Access the `artifact-id` values in downstream steps using the `outputs` xref:dsl-syntax:contexts.adoc[context].

* For all artifact ID values in JSON format provided by the action, use: `${{ steps.<action_step_name>.outputs.artifact-id }}`.

* For a specific artifact ID value use: `${{ fromJSON(steps.<action_step_name>.outputs.artifact-id).<destination URL>}}`.

=== Full workflow example

The following workflow example:

* Checks out source code from a repository.
* Configures Docker credentials.
* Builds and publishes a container image with Kaniko.
* Promotes the image to AWS ECR.
* Accesses the `artifact-id` value in the step to promote the image to ECR.

[source,yaml,role="default-expanded"]
----
apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: workflow
on:
  push:
    branches:
      - "*"

permissions:
  scm-token-own: read
  scm-token-org: read
  id-token: read

jobs:
  build:
    steps:
      - name: Check out
        uses: cloudbees-io/checkout@v1
        with:
          repository: my-name/my-repo-name
      - id: dockerconfig
        name: Configure container registry credentials
        uses: cloudbees-io/configure-oci-credentials@v1
        with:
          registry: ${{ vars.DOCKER_REGISTRY }}
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build-with-Kaniko
        uses: cloudbees-io/kaniko@v1
        kind: build
        with:
          destination: ${{ vars.DOCKER_REGISTRY }}:latest
          dockerfile: my-dockerhub/docker/config.json
      - name: Promote an image in ECR
        uses: cloudbees-io/ecr-promote-image@v1
        with:
           registry-url: ${{ secrets.AWS_ECR_PATH }}
           source-repository-name: my-repo-name
           target-repository-name: ${{ fromJSON(steps.build-with-kaniko.outputs.artifact-id).${{ secrets.AWS_ECR_PATH }} }}
           source-tag: ${{ vars.DOCKER_REGISTRY }}:latest
           target-tag: ${{ secrets.AWS_ECR_PATH }}:latest
----

== License

This code is made available under the 
link:https://opensource.org/license/mit/[MIT license].

== References

* Learn more about link:https://docs.cloudbees.com/docs/cloudbees-platform/latest/actions[using actions in CloudBees workflows].
* Learn about link:https://docs.cloudbees.com/docs/cloudbees-platform/latest/[the CloudBees platform].
