= CloudBees action: Build and publish Docker images with Kaniko

Use the Kaniko action to build images based upon a Dockerfile, then publish the image to a Docker registry.
Kaniko builds images inside a container or Kubernetes cluster.
This action also reports the image and tag names to the workflow run for artifact traceability purposes.

== Prerequisites

. To authenticate with the Docker registry, you must have a Docker config file in the `${HOME}/.docker/config.json` path.
+
Use link:https://github.com/cloudbees-io/configure-oci-credentials[the OCI credentials configuration action] to generate a Docker config file, as in the following example.
+
In your YAML file, add:
+
[source,yaml]
----

      - id: dockerconfig
        name: Configure container registry credentials
        uses: cloudbees-io/configure-oci-credentials@v1
        with:
          registry: ${{ vars.DOCKER_REGISTRY }}
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

----

. The Docker config file must be formatted in JSON.
To use the following example, replace:
+
* <REGISTRY_HOST> with your registry host URL.
* <USERNAME> with your username.
* <PASSWORD> with your password.
+
NOTE: The `+"auth":"<USERNAME>:<PASSWORD>"+` field must be base64-encoded.
+
[source,json,role="novalidate"]
----
{
	"auths": {
		"<REGISTRY_HOST>": {
			"username": "<USERNAME>",
			"password": "<PASSWORD>",
			"auth": "<USERNAME>:<PASSWORD>"
		}
	}
}
----

== Inputs

[cols="30%,15%,15%,40%",options="header"]
.Input details
|===

| Input name
| Data type
| Required?
| Description

| `destination`
| String
| Yes
| The locations of the target images to be published.
Formatted as a comma-separated list for passing multiple images.

| `build-args`
| String
| No
| The build arguments to be passed to the Kaniko build.
Formatted as a comma-separated list for passing multiple build arguments.

| `context`
| String
| No
| The path to the build context.
Default is `${{ cloudbees.workspace }}`.

| `dockerfile`
| String
| No
| The path to the Dockerfile to be built.
Default is `Dockerfile`.

| `labels`
| String
| No
| The label metadata added to the final image.
Formatted as a comma-separated list for passing multiple labels.

| `registry-mirrors`
| String
| No
| Registry mirrors to use for loading images.
Formatted as a comma-separated list for passing multiple registries.

| `skip-default-registry-fallback`
| Boolean
| No
| If set to 'true', fails build if `registry-mirrors` cannot pull the image.
If `registry-mirrors` is empty, this flag is ignored.
Default is 'false'.

| `tar-path`
| String
| No
| Full path location where the image is to be saved, including the filename.
To use this option, the image file must be in the TAR format.

| `verbosity`
| String
| No
| The verbosity of logging when running the Kaniko build.
Accepted inputs are: `panic`, `fatal`, `error`, `warn`, `info`, `debug`, `trace`.
Default is `info`.

|===

== Output

[cols="30%,20%,50%",options="header"]
.Output details
|===

| Output name
| Data type
| Description

| `artifactIds`
| String
| The unique identifier of the artifact reported to the CloudBees platform.
|===

=== Using the action output

Access the `artifactIds` values in downstream steps using the `outputs` xref:dsl-syntax:contexts.adoc[context].
To use the following examples, replace <ACTION_STEP_NAME> with the action step name, and <DESTINATION_URL> with the destination URL.

* For all artifact ID values in JSON format provided by the action, use: `${{ steps.<ACTION_STEP_NAME>.outputs.artifactIds }}`.

* For a specific artifact ID value use: `${{ fromJSON(steps.<ACTION_STEP_NAME>.outputs.artifactIds).<DESTINATION_URL>}}`.

== Usage examples

=== Basic example

The following is a basic usage example for this action:

[source,yaml]
----
      - name: Build a container image with Kaniko
        uses: cloudbees-io/kaniko@v1
        with:
          destination: path/to/registry/host/my-image:1.0.1,path/to/registry/host/my-image:latest
----

=== Using optional inputs

The following example specifies optional inputs:

[source,yaml]
----
      - name: Kaniko build with optional inputs
        uses: cloudbees-io/kaniko@v1
        with:
          destination: path/to/registry/host/my-image:1.0.1,path/to/registry/host/my-image:latest
          build-args: BUILDKIT_CONTEXT_KEEP_GIT_DIR=1,BUILDKIT_INLINE_CACHE=1
          context: .
          dockerfile: path/to/Dockerfile
          labels: maintainer=John Smith,version=1.0.1
          tar-path: path/to/image.tar
          verbosity: warn

----

=== Full workflow example

The following workflow example:

* Checks out source code from a repository.
* Configures Docker credentials.
* Builds and publishes a container image with Kaniko.
* Prints the artifact IDs for both static and dynamically created destinations.
* Promotes the image to AWS ECR.
* Accesses the `artifactIds` value in the step to promote the image to ECR.

[source,yaml,role="default-expanded"]
----
apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: workflow
on:
  push:
    branches:
      - "*"

permissions:
  scm-token-own: read
  scm-token-org: read
  id-token: read

jobs:
  build:
    steps:
      - name: Check out
        uses: cloudbees-io/checkout@v1
        with:
          repository: my-name/my-repo-name
      - name: Configure container registry credentials
        id: dockerconfig
        uses: cloudbees-io/configure-oci-credentials@v1
        with:
          registry: ${{ vars.DOCKER_REGISTRY }}
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build with Kaniko
        id: build
        uses: cloudbees-io/kaniko@v1
        kind: build
        with:
          destination: ${{ vars.DOCKER_REGISTRY }}:latest
          dockerfile: my-dockerhub/docker/config.json
      - name: Print output parameter artifact IDs from Kaniko action
        id: echo-artifact-ids
        uses: docker://alpine:latest
        shell: sh
        run: |
          echo "artifact IDs output parameter values: ${{ steps.build-with-kaniko.outputs.artifactIds }}"
          echo "single artifact ID for the static destination '<registry host>/<image name>:latest': ${{ fromJSON(steps.kaniko-build.outputs.artifactIds)['<registry host>/<image name>:latest'] }}"
          echo "single artifact ID for the dynamically created destination '${{ env.DYNAMIC_DESTINATION }}': ${{ fromJSON(steps.kaniko-build.outputs.artifactIds)[env.DYNAMIC_DESTINATION] }}"
        env:
          DYNAMIC_DESTINATION:  "<registry host>/<image name>:-${{ cloudbees.version }}"
      - name: Promote an image in ECR
        uses: cloudbees-io/ecr-promote-image@v1
        with:
           registry-url: ${{ secrets.AWS_ECR_PATH }}
           source-repository-name: my-repo-name
           target-repository-name: ${{ fromJSON(steps.build-with-kaniko.outputs.artifactIds).${{ secrets.AWS_ECR_PATH }} }}
           source-tag: ${{ vars.DOCKER_REGISTRY }}:latest
           target-tag: ${{ secrets.AWS_ECR_PATH }}:latest

----

== License

This code is made available under the 
link:https://opensource.org/license/mit/[MIT license].

== References

* Learn more about link:https://docs.cloudbees.com/docs/cloudbees-platform/latest/actions[using actions in CloudBees workflows].
* Learn about link:https://docs.cloudbees.com/docs/cloudbees-platform/latest/[the CloudBees platform].
