= CloudBees action: Build and publish Docker images with Kaniko

Use the Kaniko action to build images based upon a Dockerfile, then publish the image to a Docker registry.
Kaniko builds images inside a container or Kubernetes cluster.
This action also reports the image and tag names to the workflow run for artifact traceability purposes.

== Prerequisites

To authenticate with the Docker registry, you must have a Docker config file in the `${HOME}/.docker/config.json` path.

Use link:https://github.com/cloudbees-io/configure-oci-credentials[the OCI credentials configuration action] to generate a Docker config file, as in the following example.

In your YAML file, add:

[source,yaml]
----

      - id: dockerconfig
        name: Configure container registry credentials
        uses: cloudbees-io/configure-oci-credentials@v1
        with:
          registry: ${{ vars.DOCKER_REGISTRY }}
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

----

The Docker config file must be formatted in JSON, as follows:

[source,json,role="novalidate"]
----
{
	"auths": {
		"<registry host>": {
			"username": "<username>",
			"password": "<password>",
			"auth": "<username>:<password>"
		}
	}
}
----

NOTE: The `+"auth":"<username>:<password>"+` field must be base64-encoded.

== Inputs

[cols="2a,1a,1a,3a",options="header"]
.Input details
|===

| Input name
| Data type
| Required?
| Description

| `dockerfile`
| String
| No
| The path to the Dockerfile to be built. Default is `Dockerfile`.

| `context`
| String
| No
| The path to the build context. Default is `${{ cloudbees.workspace }}`.

| `destination`
| String
| Yes
| The target image to be published. Formatted as a CSV list, so you can pass multiple images.

| `tar-path`
| String
| No
| Full path including the filename where the image TAR file should be saved. This option allows saving the built image as a tarball.

| `build-args`
| String
| No
| The build arguments to be passed to the Kaniko build. Formatted as a CSV list, so you can pass multiple build arguments.

| `labels`
| String
| No
| The label metadata added to the final image. Formatted as a CSV list, so you can pass multiple labels.

| `registry-mirrors`
| String
| No
| Registry mirror(s) to use for loading images. Formatted as a CSV list, so you can pass multiple registries.

| `skip-default-registry-fallback`
| String
| No
| If set, fails build if registry-mirrors cannot pull image. If registry-mirrors is empty, this flag is ignored. Accepts 'true' or 'false', default is 'false'.

| `verbosity`
| String
| No
| The verbosity of logging when running the Kaniko build. It can be one of: `panic`, `fatal`, `error`, `warn`, `info`, `debug`, `trace`. Default is `info`.

|===

== Outputs

[cols="2a,1a,3a",options="header"]
.Output details
|===

| Output name
| Data type
| Description

| `artifactIds`
| String
| The output parameter for artifact IDs.

These artifact IDs values can be accessed in subsequent steps using the outputs context. For example, to return:

* All artifact ID values provided by action in JSON format use: `${{ steps.<action_step_name>.outputs.artifactIds }}`.

* A specific artifact ID value use: `${{ fromJSON(steps.<action_step_name>.outputs.artifactIds).<destination URL>}}`.
For instance kaniko action was used in the step with name "kaniko-build", and the destination URL is `registry.example.com/my-image:latest`, then you can access the artifact ID using:
`${{ fromJSON(steps.kaniko-build.outputs.artifactIds)['registry.example.com/my-image:latest'] }}`. In case of multiple destination URLs, you can access each one by its key. And if destination URL is dynamically.


|===

== Usage example

In your YAML file, add:

[source,yaml]
----
      - name: Build a container image with Kaniko
        uses: cloudbees-io/kaniko@v1
        with:
          dockerfile: path/to/Dockerfile
          context: .
          destination: <registry host>/<image name>:1.0.1,<registry host>/<image name>:latest
          build-args: BUILDKIT_CONTEXT_KEEP_GIT_DIR=1,BUILDKIT_INLINE_CACHE=1
          labels: maintainer=John Smith,version=1.0.1
          verbosity: info
          tar-path: path/to/save/image.tar

----

== License

This code is made available under the 
link:https://opensource.org/license/mit/[MIT license].

== References

* Learn more about link:https://docs.cloudbees.com/docs/cloudbees-platform/latest/actions[using actions in CloudBees workflows].
* Learn about link:https://docs.cloudbees.com/docs/cloudbees-platform/latest/[the CloudBees platform].
