apiVersion: automation.cloudbees.io/v1alpha1
kind: action
name: 'Kaniko build and push'
description: 'Build and publish Docker images from a Dockerfile using Kaniko. Optionally, save the image as a tar file.'

inputs:
  dockerfile:
    description: 'Path to the Dockerfile'
    default: Dockerfile
  context:
    description: 'Docker build context'
    default: ${{ cloudbees.workspace }}
  destination:
    description: >
      Target image(s) that will be published to the registries configured in the file ${HOME}/.docker/config.json
      Type: CSV
    required: true
  tar-path:
    description: 'Full path, including filename, where the image tar file should be saved.'
    required: false
  build-args:
    description: >
      Docker build arguments.
      Type: CSV
  labels:
    description: >
      Metadata to be associated with the resulting image.
      Type: CSV
  target:
    description: >
      Build a specific target stage in a multi-stage Dockerfile.
      Type: string
  registry-mirrors:
    description: >
      Registry mirror(s) to use for loading images.
      Type: CSV
  registry-configuration:
    description: >
      CloudBees registry configuration file containing the registries to use for loading images.
      By default it uses the file containing the registries configured under 'Integrations' in the CloudBees platform.
    default: ${{ cloudbees.registries }}
  skip-default-registry-fallback:
    default: 'false'
    description: >
      If set, fails build if registry-mirrors cannot pull image. If registry-mirrors is empty, this flag is ignored.
      Type: Boolean
  verbosity:
    default: info
    description: >
      Log level verbosity - panic, fatal, error, warn, info, debug, trace
  commit:
    description: >
      The commit ID from the source repository, used when registering the build artifact in CloudBees platform.
    default: ${{ cloudbees.scm.sha }}
  repository-url:
    description: >
      The clone URL of the source repository, used when registering the build artifact in CloudBees platform.
    default: ${{ cloudbees.scm.repositoryUrl }}
  ref:
    description: >
      The tag or branch of the source repository, used when registering the build artifact in CloudBees platform.
    default: ${{ cloudbees.scm.ref }}
  artifact-name:
    description: >
      The name of the build artifact as it will be registered.
      By default, the artifact name is derived from the image repository name.
    required: false
  component-id:
    description: >
      The ID of the component associated with the artifact. If not provided, the artifact is registered with the component of the current workflow run.
    default: ${{cloudbees.component.id}}
    required: false

  kaniko-dir:
    description: >
      Path to the Kaniko working directory. If set, it is passed as --kaniko-dir to the executor
      then KANIKO_DIR will be set as environment variable.
    required: false

outputs:
  digest:
    value: ${{ steps.imgbuild.outputs.digest }}
    description: Image digest (image ID)
  tag:
    value: ${{ steps.imgbuild.outputs.tag }}
    description: Tag of the first pushed image
  tag-digest:
    value: ${{ steps.imgbuild.outputs.tag-digest }}
    description: |
      Tag of the first specified destination along with the image digest.
      Please note that this format is not part of the OCI standard but supported by most container tools.
      Tools loading such an image reference ignore the tag but perform the lookup based on the image repository and digest only.
      The tag only serves as a hint for humans.
      Using this format guarantees that the image is continued to be used even when the tag was overwritten and prevents stale image caches on different nodes.
  image:
    value: ${{ steps.imgbuild.outputs.image }}
    description: |
      Image reference of the first specified destination, including the image digest.
      Please note that this image reference format is not part of the OCI standard but supported by most container tools.
      Tools loading such an image reference ignore the tag but perform the lookup based on the image repository and digest only.
      The tag only serves as a hint for humans.
      Using this image reference format guarantees that the image is continued to be used even when the tag was overwritten and prevents stale image caches on different nodes.
  artifact-ids:
    value: ${{ steps.register-build-artifacts.outputs.artifact-ids }}
    description: |
      Artifact IDs for the published images reported to the workflow run for artifact traceability purposes.

runs:
  using: composite
  steps:
    - id: imgbuild
      name: Build, publish, and optionally save Docker image as a tar archive.
      uses: docker://020229604682.dkr.ecr.us-east-1.amazonaws.com/actions/kaniko-action:${{ action.scm.sha }}
      with:
        entrypoint: /kaniko/cloudbees-kaniko-action
        args: |
          --dockerfile "${{ inputs.dockerfile }}"
          --context "${{ inputs.context }}"
          --destination "${{ inputs.destination }}"
          --registry-mirrors "${{ inputs.registry-mirrors }}"
          --skip-default-registry-fallback="${{ inputs.skip-default-registry-fallback }}"
          --verbosity "${{ inputs.verbosity }}"
          --target "${{ inputs.target }}"
          ${{ inputs.kaniko-dir && format('--kaniko-dir "{0}"', inputs.kaniko-dir) || '' }}
          ${{ inputs.tar-path && format('--tar-path "{0}"', inputs.tar-path) || '' }}
      env:
        DOCKER_CONFIG: ${{ cloudbees.home }}/.docker
        DOCKER_BUILD_ARGS: ${{ inputs.build-args }}
        DOCKER_LABELS: ${{ inputs.labels }}
        CLOUDBEES_REGISTRY_CONFIG: ${{ inputs.registry-configuration }}
        CLOUDBEES_API_URL: ${{ cloudbees.api.url }}
        CLOUDBEES_API_TOKEN: ${{ cloudbees.api.token }}
        CLOUDBEES_RUN_ID: ${{ cloudbees.run_id }}
        CLOUDBEES_RUN_ATTEMPT: ${{ cloudbees.run_attempt }}
        INPUT_REPOSITORY_URL: ${{ inputs.repository-url }}
        INPUT_COMMIT: ${{ inputs.commit }}
        INPUT_REF: ${{ inputs.ref }}
        INPUT_ARTIFACT_NAME: ${{ inputs.artifact-name }}
        INPUT_COMPONENT_ID: ${{ inputs.component-id }}

    - id: prepare-register-build-artifacts
      if: ${{ steps.imgbuild.outputs.artifact-ref != '' }}
      name: Prepare to register build artifacts
      uses: docker://esolang/jq:latest
      run: |

        json='${{ steps.imgbuild.outputs.artifact-ref }}'

        if [ "$VERBOSITY" = "debug" ] || [ "$VERBOSITY" = "trace" ]; then
          echo "Received artifact reference JSON: $json"
        fi

        artifact_json=$(echo "$json" | /usr/bin/jq \
          --arg component "$COMPONENT_ID" \
          --arg commit "$COMMIT" \
          --arg repo "$REPOSITORY_URL" \
          --arg ref "$REF" \
          --arg artifactName "$ARTIFACT_NAME" \
          --arg type "docker" '
          map(
            {
              name: (if $artifactName != "" then $artifactName else .name end),
              version: .version,
              digest: .digest,
              url: .url,
              commit: $commit,
              repositoryUrl: $repo,
              ref: $ref,
              componentId: $component,
              type: $type
            }
          )
        ')

        if [ "$VERBOSITY" = "debug" ] || [ "$VERBOSITY" = "trace" ]; then
          echo "Prepared artifact metadata: $artifact_json"
        fi

        # Store the final payload in output
        echo -n "$artifact_json" > $CLOUDBEES_OUTPUTS/artifact-metadata

      env:
        ARTIFACT_NAME: ${{ inputs.artifact-name }}
        COMMIT: ${{ inputs.commit }}
        REPOSITORY_URL: ${{ inputs.repository-url }}
        REF: ${{ inputs.ref }}
        COMPONENT_ID: ${{ inputs.component-id }}
        VERBOSITY: ${{ inputs.verbosity }}

    - id: register-build-artifacts
      name: Register an artifact with the CloudBees Unify
      uses: cloudbees-io/register-build-artifacts@v1
      with:
        artifact-metadata: ${{ steps.prepare-register-build-artifacts.outputs.artifact-metadata }}
