FROM alpine:3.21 AS build
RUN echo test > /test-file

FROM docker.io/mgoltzsche/podman:5.4.0-minimal AS podman

FROM scratch
COPY --from=build /test-file /test-file
COPY --from=podman /usr/local/bin/crun /usr/local/bin/crun

# Canary line — should be deleted by sed patch
RUN busybox echo "This should be removed"

# Another canary (CMD)
CMD ["busybox", "sh"]

ENTRYPOINT ["/usr/local/bin/crun"]
