FROM alpine:3.21 AS build
RUN echo test > /test-file
RUN addgroup -g 1000 nonroot && adduser -D -u 1000 -G nonroot nonroot
RUN mkdir -p /etc && echo "nonroot:x:1000:1000:nonroot:/home/nonroot:/sbin/nologin" > /etc/passwd && echo "nonroot:x:1000:" > /etc/group

FROM docker.io/mgoltzsche/podman:5.4.0-minimal AS podman

FROM scratch
COPY --from=build /test-file /test-file
COPY --from=build /etc/passwd /etc/passwd
COPY --from=build /etc/group /etc/group
COPY --from=podman /usr/local/bin/crun /usr/local/bin/crun
ENTRYPOINT ["/usr/local/bin/crun"]
