name: kaniko-action
apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow

on:
  push:
    branches:
      - '**'
jobs:
  build:
    env:
      DOCKERCONFIGJSON: ${{ secrets.dockerconfigjson }}
    steps:
    - name: get source code
      uses: docker://alpine/git:v2.36.3
      shell: sh
      run: |
        git clone https://${{secrets.GIT_SECRET_ACCESS_TOKEN}}@github.com/cloudbees-io/kaniko .
        echo "scm branch: ${{ cloudbees.scm.branch }}"
        echo "scm sha: ${{ cloudbees.scm.sha }}"
        echo "scm repo: ${{ cloudbees.scm.repository }}"
        echo "scm provider: ${{ cloudbees.scm.provider }}"
        echo "scm provider_url: ${{ cloudbees.scm.provider_url }}"
        echo "workspace: ${{ cloudbees.workspace }}"
    - name: docker build and publish
      uses: cloudbees-io/kaniko@SDP-3696
      with:
        dockerconfigjson: ${{ secrets.dockerconfigjson }}
        destination: registry.saas-dev.beescloud.com/staging/kaniko-action:${{ cloudbees.scm.branch }}${{ cloudbees.scm.branch == 'main' && ',registry.saas-dev.beescloud.com/staging/kaniko-action:latest' || '' }}
        labels: maintaner=sdp-pod-3,email=engineering@cloudbees.io
        context: ${{ cloudbees.workspace }}
