name: kaniko-action
apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow

on:
  push:
    branches:
      - '**'

permissions:
  id-token: write

jobs:
  build-base-kaniko-image:
    steps:
    - name: Checkout this repo (for workflow, scripts, etc.)
      uses: cloudbees-io/checkout@v1

    - name: Checkout Kaniko upstream repo into subdir
      uses: cloudbees-io/checkout@v1
      with:
        repository: chainguard-dev/kaniko
        path: kaniko-src
        ref: v1.25.0

    - name: Login to AWS
      uses: cloudbees-io/configure-aws-credentials@v1
      with:
        aws-region: us-east-1
        role-to-assume: ${{ vars.oidc_staging_iam_role }}
        role-duration-seconds: "3600"

    - name: Configure container registry for ECR
      uses: cloudbees-io/configure-ecr-credentials@v1

    - name: Append GOFLAGS and patch Dockerfile
      uses: docker://golang:1.24.0
      run: |
        cd kaniko-src

        # Insert GOFLAGS after ARG TARGETOS
        sed -i '/^ARG TARGETOS/a ARG GOFLAGS="-buildvcs=false"' deploy/Dockerfile

        # Remove lines containing busybox
        # sed -i '/RUN.*busybox/d' deploy/Dockerfile
        # sed -i '/CMD.*busybox/d' deploy/Dockerfile

        # Optionally commit changes if needed
        git config user.name "ci"
        git config user.email "ci@example.com"
        git add deploy/Dockerfile
        git commit -m "Patch Dockerfile: add GOFLAGS, remove busybox"


    - name: Build patched Kaniko image
      id: build-image
      uses: cloudbees-io/kaniko@v1
      with:
        context: ./kaniko-src
        dockerfile: deploy/Dockerfile
        destination: 020229604682.dkr.ecr.us-east-1.amazonaws.com/actions/chainguard-dev-kaniko-base:${{ cloudbees.scm.sha }},020229604682.dkr.ecr.us-east-1.amazonaws.com/actions/chainguard-dev-kaniko-base:test

    - name: Run TruffleHog on base image
      uses: cloudbees-io/trufflehog-secret-scan-container@v1
      with:
        image-location: 020229604682.dkr.ecr.us-east-1.amazonaws.com/actions/chainguard-dev-kaniko-base
        image-tag: ${{ cloudbees.scm.sha }}

  build:
    needs: [build-base-kaniko-image]
    steps:
    - name: Get source code
      uses: cloudbees-io/checkout@v1

    - name: Validate action
      uses: docker://amazon/aws-cli:2.12.6
      run: |
        TESTING_SHA=$(cat .cloudbees/testing/action.yml | sha1sum)
        ORIGINAL_SHA=$(sed -e 's|docker://public.ecr.aws/l7o7z1g8/actions/|docker://020229604682.dkr.ecr.us-east-1.amazonaws.com/actions/|g' < action.yml | sha1sum)
        if [ "${TESTING_SHA}" != "${ORIGINAL_SHA}" ]; then
          echo "Original action different from testing action"
          exit 1
        fi

    - name: Unit tests
      uses: docker://golang:1.24.0
      run: |
        go test --cover ./...

    - name: Login to AWS
      uses: cloudbees-io/configure-aws-credentials@v1
      with:
        aws-region: us-east-1
        role-to-assume: ${{ vars.oidc_staging_iam_role }}
        role-duration-seconds: "3600"

    - name: Configure container registry for ECR
      uses: cloudbees-io/configure-ecr-credentials@v1

    - name: Build image
      id: build-image
      uses: cloudbees-io/kaniko@v1
      with:
        destination: 020229604682.dkr.ecr.us-east-1.amazonaws.com/actions/kaniko-action:${{ cloudbees.scm.sha }},020229604682.dkr.ecr.us-east-1.amazonaws.com/actions/kaniko-action:latest
        labels: maintainer=sdp-pod-3,email=engineering@cloudbees.io
        registry-mirrors: 020229604682.dkr.ecr.us-east-1.amazonaws.com/docker-hub

    - name: Run TruffleHog Container Action
      uses: cloudbees-io/trufflehog-secret-scan-container@v1
      with:
        image-location: 020229604682.dkr.ecr.us-east-1.amazonaws.com/actions/kaniko-action
        image-tag: ${{ cloudbees.scm.sha }}
  
  test:
    needs: [build]
    steps:
    - name: Get source code
      uses: cloudbees-io/checkout@v1

    - name: Login to AWS
      uses: cloudbees-io/configure-aws-credentials@v1
      with:
        aws-region: us-east-1
        role-to-assume: ${{ vars.oidc_staging_iam_role }}
        role-duration-seconds: "3600"

    - name: Configure container registry for ECR
      uses: cloudbees-io/configure-ecr-credentials@v1

    - name: Build test image
      id: build
      uses: ./.cloudbees/testing
      with:
        context: ./.cloudbees/testing
        dockerfile: Dockerfile-test
        destination: 020229604682.dkr.ecr.us-east-1.amazonaws.com/actions/kaniko-action-test:${{ cloudbees.scm.sha }}
        skip-default-registry-fallback: 'true'
        registry-mirrors: 020229604682.dkr.ecr.us-east-1.amazonaws.com/docker-hub
        verbosity: debug
        tar-path: ${{ cloudbees.home }}/image.tar

    - name: Check test image
      uses: docker://gcr.io/go-containerregistry/crane:debug
      env:
        GOLDEN_FILE: .cloudbees/testing/expected-paths.txt
      run: |
        EXPECTED=${{ steps.build.outputs.digest }}
        ACTUAL=`crane digest 020229604682.dkr.ecr.us-east-1.amazonaws.com/actions/kaniko-action-test:${{ cloudbees.scm.sha }} --platform linux/amd64`
        if [ "$EXPECTED" != "$ACTUAL" ]; then
          echo "FAIL: Expected image digest $EXPECTED, but got $ACTUAL"
          exit 1
        fi

        if stat "${{ cloudbees.home }}/image.tar"; then
          echo "Kaniko action wrote tar file."
        else
          echo "FAIL: Kaniko action did not write tar file."
          exit 1
        fi

        crane export "020229604682.dkr.ecr.us-east-1.amazonaws.com/actions/kaniko-action-test:${{ cloudbees.scm.sha }}" /tmp/image-rootfs.tar
        mkdir /tmp/image-rootfs
        tar -xf /tmp/image-rootfs.tar -C /tmp/image-rootfs/
        (cd /tmp/image-rootfs && find . | sort) > /tmp/actual-paths.txt
        echo
        echo ACTUAL ROOTFS:
        cat /tmp/actual-paths.txt | sed -E 's/^/  /'
        echo
        if [ "$(comm -3 $GOLDEN_FILE /tmp/actual-paths.txt)" ]; then
          echo "FAIL: The built test image's rootfs content paths don't match the expected ones defined in $GOLDEN_FILE!"
          comm -3 $GOLDEN_FILE /tmp/actual-paths.txt
          exit 1
        fi
