name: kaniko-action
apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow

on:
  push:
    branches:
      - '**'

permissions:
  id-token: write

jobs:
  build:
    steps:
    - name: Get source code
      uses: cloudbees-io/checkout@v1

    - name: Validate action
      uses: docker://amazon/aws-cli:2.12.6
      run: |
        TESTING_SHA=$(cat .cloudbees/testing/action.yml | sha1sum)
        ORIGINAL_SHA=$(sed -e 's|docker://public.ecr.aws/l7o7z1g8/actions/|docker://020229604682.dkr.ecr.us-east-1.amazonaws.com/actions/|g' < action.yml | sha1sum)
        if [ "${TESTING_SHA}" != "${ORIGINAL_SHA}" ]; then
          echo "Original action different from testing action"
          exit 1
        fi

    - name: Unit tests
      uses: docker://golang:1.20-alpine3.18
      run: |
        go test --cover ./...

    - name: Login to AWS
      uses: cloudbees-io/configure-aws-credentials@v1
      with:
        aws-region: us-east-1
        role-to-assume: ${{ vars.oidc_staging_iam_role }}
        role-duration-seconds: "3600"

    - name: Configure container registry for ECR
      uses: cloudbees-io/configure-ecr-credentials@v1

    - name: Login to Dockerhub using CloudBees service account
      uses: cloudbees-io/configure-oci-credentials@v1
      with:
        registry: docker.io
        username: ${{ secrets.e5bbc3_dockerhub_user }}
        password: ${{ secrets.e5bbc3_dockerhub_password }}

    - name: Build image
      id: build-image
      uses: cloudbees-io/kaniko@v1
      with:
        destination: 020229604682.dkr.ecr.us-east-1.amazonaws.com/actions/kaniko-action:${{ cloudbees.scm.sha }}
        labels: maintainer=sdp-pod-3,email=engineering@cloudbees.io
  
  test:
    needs: [build]
    steps:
    - name: Get source code
      uses: cloudbees-io/checkout@v1

    - name: Login to AWS
      uses: cloudbees-io/configure-aws-credentials@v1
      with:
        aws-region: us-east-1
        role-to-assume: ${{ vars.oidc_staging_iam_role }}
        role-duration-seconds: "3600"

    - name: Configure container registry for ECR
      uses: cloudbees-io/configure-ecr-credentials@v1

    - name: Login to Dockerhub using CloudBees service account
      uses: cloudbees-io/configure-oci-credentials@v1
      with:
        registry: docker.io
        username: ${{ secrets.e5bbc3_dockerhub_user }}
        password: ${{ secrets.e5bbc3_dockerhub_password }}

    - name: Build test image
      id: build
      uses: ./.cloudbees/testing
      with:
        context: ./.cloudbees/testing
        dockerfile: Dockerfile-test
        destination: 020229604682.dkr.ecr.us-east-1.amazonaws.com/actions/kaniko-action-test:${{ cloudbees.scm.sha }}
        skip-default-registry-fallback: 'false'

    - name: Check test image
      uses: docker://alpine:3.18
      run: |
        apk add -U --no-cache curl ca-certificates
        curl -L https://github.com/regclient/regclient/releases/latest/download/regctl-linux-amd64 >/usr/local/bin/regctl
        chmod 755 /usr/local/bin/regctl

        EXPECTED=${{ steps.build.outputs.digest }}
        ACTUAL=`regctl image digest 020229604682.dkr.ecr.us-east-1.amazonaws.com/actions/kaniko-action-test:${{ cloudbees.scm.sha }}`
        if [ "$EXPECTED" != "$ACTUAL" ]; then
          echo "expected $EXPECTED, but got $ACTUAL"
          exit 1
        fi